routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {

Route::get('logout',function(){
    Session::flush();
    Auth::logout();
    return redirect(route('login'));
});

Route::get('/', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('art','ArtController');
Route::delete('art-photo-delete/{artPhoto}', 'ArtController@deletePhoto')->name('art.photo.delete');
Route::get('order', 'OrderController@index')->name('order.index');

Route::get('student/art', 'Student\ArtController@index')->name('student.art.index');
Route::get('student/art/{art}', 'Student\ArtController@show')->name('student.art.show');

Route::get('rent-art/{art}', 'Student\ArtController@rent')->name('student.art.rent');
Route::post('rent-art/{art}', 'Student\ArtController@confirm')->name('student.art.confirm');

Route::get('order-success/{order}', 'Student\OrderController@success')->name('order.success');
Route::get('student/order', 'Student\OrderController@index')->name('student.order.index');
Route::get('send-back/{order}', 'Student\OrderController@sendBack')->name('student.order.send.back');
});

app/Art.php
<?php

namespace App;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;

class Art extends Model
{
    protected $fillable = [
      'name',
      'material',
      'description',
      'price',
      'status'
    ];

    public static function uploadPictures($art, $request)
    {
        if($request->hasFile('pictures')){
            foreach($request->allFiles()['pictures'] as $file){
                $name = $file->getClientOriginalName();
                $imageName = time().'_'.$name;
                $path = '/artwork-pictures/'.$art->id;
                if($file->move(public_path($path), $imageName)){
                    ArtPhoto::create(['art_id'=>$art->id,'name'=>$imageName,'path'=>$path]);
                }
            }
        }
    }

    public static function confirm($art, $request)
    {
        if($request->get('address_select') != null) {
          $address_id = $request->get('address_select');
        }
        if($request->get('street') != null && $request->get('street') != '') {
            $address = Auth::user()->addresses()->create([
                'street'=>$request->get('street'),
                'number'=>$request->get('number'),
                'suffix'=>$request->get('suffix'),
                'zip_code'=>$request->get('zip_code'),
                'city'=>$request->get('city'),
                'country'=>$request->get('country'),
            ]);
            $address_id = $address->id;

        }

        return Order::create([
            'user_id' => Auth::user()->id,
            'art_id' => $art->id,
            'address_id'=>$address_id,
            'amount_of_months' => $request->get('period_select'),
            'price' => (double) $art->price,
            'payment_id' => 'not_paid',
            'paid' => false,
        ]);
    }

    public function artPhotos()
    {
        return $this->hasMany(ArtPhoto::class);
    }

    public function orders()
    {
      return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/ArtController.php
<?php

namespace App\Http\Controllers;

use App\Art;
use App\ArtPhoto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ArtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = view('art.index');
        $view->artworks = Art::all();
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view('art.create');

        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        if($data['price'] > 50000) {
            $data['price'] = 50000;
        }

        $art = Art::create($data);

        Art::uploadPictures($art, $request);

        return redirect()->route('art.index')->with('success', 'Artwork stored');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Art $art)
    {
        $view = view('art.edit');
        $view->art = $art;
        $view->photos = $art->artPhotos;
        return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Art $art)
    {
        $data = $request->all();

        if($data['price'] > 50000) {
            $data['price'] = 50000;
        }

        $art->update($data);

        Art::uploadPictures($art, $request);
        
        return redirect(route('art.index'))->with('success', 'Successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Art $art)
    {
        $art->delete();
        return redirect()->back()->with('success', 'Artwork deleted');
    }

    public function deletePhoto(ArtPhoto $artPhoto)
    {
        $artPhoto->delete();
        return redirect()->back()->with('success', 'Photo deleted');
    }
}

app/Http/Controllers/Student/ArtController.php
<?php

namespace App\Http\Controllers\Student;

use App\Art;
use App\ArtPhoto;
use App\Order;
use App\Address;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ArtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = view('student.art.index');
        $view->artworks = Art::where('status','available')->get();
        return $view;
    }

    /**
     * Display the specified resource.
     *
     * @param  Art  $art
     * @return \Illuminate\Http\Response
     */
    public function show(Art $art)
    {
        $view = view('student.art.show');
        $view->art = $art;
        return $view;
    }

    /**
     * Display the specified resource to rent art.
     *
     * @param  Art  $art
     * @return \Illuminate\Http\Response
     */
    public function rent(Art $art)
    {
        $view = view('student.art.rent');
        $view->art = $art;
        $view->addresses = Auth::user()->addresses;
        return $view;
    }

    /**
     * Create the order
     *
     * @param  Art  $art
     * @param  Request  $request
     * @return \Illuminate\Http\Response
     */
    public function confirm(Request $request, Art $art)
    {

        $order = Art::confirm($art, $request);

        $redirectUrl = Order::preparePayment($order);
        return redirect($redirectUrl, 303);
    }
}

resources/views/art/create.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-7">
                    <form action="{{route('art.store')}}" method="post" enctype="multipart/form-data">
                    @csrf

                    <div class="card">
                        <div class="card-header">
                            <small>Upload new </small>
                            <strong>Artwork!</strong>
                        </div>
                        <div class="card-body card-block">
                            @include('art.form')
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/art/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content art_edit_section section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-7">
                  {{Form::open(['route'=>['art.update', $art->id], 'method'=>'put', 'enctype' => 'multipart/form-data'])}}
                        <div class="card">
                            <div class="card-header">
                                <small>Edit </small>
                                <strong>{{$art->name}}</strong>
                            </div>
                            <div class="card-body card-block">
                                @include('art.form')
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="fa fa-dot-circle-o"></i> Submit
                            </button>
                        </div>
                    {{Form::close()}}
                </div>
                <div class="col-5">
                    @foreach($photos as $photo)
                      <div class="row">
                        <div class="col-10">
                          <div class="images">
                            <img src="{{asset($photo->path.'/'.$photo->name)}}"/>
                          </div>
                        </div>
                        <div class="col-2">
                          {{Form::open(['route'=>['art.photo.delete', $photo], 'method'=>'delete'])}}
                          <button type="submit" class="btn btn-danger" onclick="return confirm('are you sure you want to delete this photo?')">delete</button>
                        </div>
                      </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/art/form.blade.php
<div class="form-group">
    <label for="name" class=" form-control-label">Name</label>
    <input type="text" id="name" name="name" placeholder="Enter the name of the artwork" class="form-control" @if(isset($art->id)) value="{{$art->name}}" @endif required>
</div>
<div class="form-group">
    <label for="material" class=" form-control-label">Material</label>
    <input type="text" id="material" name="material" placeholder="Enter the material" class="form-control" @if(isset($art->id)) value="{{$art->material}}" @endif required>
</div>
<div class="form-group">
    <label for="description" class=" form-control-label">Description</label>
    <textarea id="description" name="description" placeholder="Enter the description" class="form-control" required>@if(isset($art->id)){{$art->description}}@endif</textarea>
</div>
<div class="form-group">
    <label for="price" class=" form-control-label">Price</label>
    <input type="text" id="price" name="price" placeholder="Enter the price in euros" class="form-control" @if(isset($art->id)) value="{{$art->price}}" @endif required>
</div>
<div class="form-group">
    <label for="pictures" class=" form-control-label">Pictures</label>
    <input type="file" id="pictures" name="pictures[]" class="form-control" multiple>
</div>

resources/views/art/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            Overview artworks
                            <a href="{{route('art.create')}}" class="btn btn-primary float-right">Add new artwork</a>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <td>Name</td>
                                    <td>Price</td>
                                    <td>Material</td>
                                    <td>Status</td>
                                    <td>#</td>
                                    <td>#</td>
                                </thead>
                                <tbody>
                                @foreach($artworks as $artwork)
                                    <tr>
                                        <td>{{$artwork->name}}</td>
                                        <td>&euro;{{$artwork->price}}</td>
                                        <td>{{$artwork->material}}</td>
                                        <td>{{$artwork->status}}</td>
                                        <td><a href="{{route('art.edit',$artwork->id)}}">edit</a></td>
                                        <td>
                                            {{Form::open(['route'=>['art.destroy', $artwork], 'method'=>'delete'])}}
                                              <button class='btn btn-danger' type="submit" onclick="return confirm('are you sure?')">delete</button>
                                            {{Form::close()}}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection