routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {

Route::get('logout',function(){
    Session::flush();
    Auth::logout();
    return redirect(route('login'));
});

Route::get('/', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('art','ArtController');
Route::delete('art-photo-delete/{artPhoto}', 'ArtController@deletePhoto')->name('art.photo.delete');
Route::get('order', 'OrderController@index')->name('order.index');

Route::get('student/art', 'Student\ArtController@index')->name('student.art.index');
Route::get('student/art/{art}', 'Student\ArtController@show')->name('student.art.show');

Route::get('rent-art/{art}', 'Student\ArtController@rent')->name('student.art.rent');
Route::post('rent-art/{art}', 'Student\ArtController@confirm')->name('student.art.confirm');

Route::get('order-success/{order}', 'Student\OrderController@success')->name('order.success');
Route::get('student/order', 'Student\OrderController@index')->name('student.order.index');
Route::get('send-back/{order}', 'Student\OrderController@sendBack')->name('student.order.send.back');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

    public function orders()
    {
      return $this->hasMany(Order::class);
    }

    public function arts()
    {
      return $this->hasMany(Art::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = view('user.index');
        $view->users = User::all();
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $view = view('user.create');
      return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        User::create([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'role_id' => $request->get('role')
        ]);

        return redirect()->route('user.index')->with('success', 'User added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
      $view = view('user.edit');
      $view->user = $user;
      return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = [
          'name' => $request->get('name'),
          'email' => $request->get('email'),
          'role_id' => $request->get('role')
        ];

        if (isset($request->password) && $request->password != '') {
            $data['password'] = Hash::make($request->get('password'));
        }

        $user->update($data);

        return redirect()->route('user.index')->with('success', 'User updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('user.index')->with('success', 'User deleted');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-7">
                    <form action="{{route('user.store')}}" method="post">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <small>Create new </small>
                            <strong>User!</strong>
                        </div>
                        <div class="card-body card-block">
                            @include('user.form')
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content art_edit_section section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-7">
                  {{Form::open(['route'=>['user.update', $user->id], 'method'=>'put',])}}
                        <div class="card">
                            <div class="card-header">
                                <small>Edit </small>
                                <strong>{{$user->name}}</strong>
                            </div>
                            <div class="card-body card-block">
                                @include('user.form')
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="fa fa-dot-circle-o"></i> Submit
                            </button>
                        </div>
                    {{Form::close()}}
                </div>
                <div class="col-4">
                    <h4>Saved addresses</h4>
                    @foreach($user->addresses as $address)
                        <div class="card">
                            <div class="card-body">
                                {{$address->street}} {{$address->number}} {{$address->suffix}}<br>
                                {{$address->zip_code}}<br>
                                {{$address->city}}<br>
                                {{$address->country}}<br>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/form.blade.php
<div class="form-group">
    <label for="name" class=" form-control-label">Name</label>
    <input type="text" id="name" name="name" placeholder="Enter the name of the artwork" class="form-control" @if(isset($user->id)) value="{{$user->name}}" @endif>
</div>
<div class="form-group">
    <label for="email" class=" form-control-label">Email</label>
    <input type="email" id="email" name="email" placeholder="Enter the email" class="form-control" @if(isset($user->id)) value="{{$user->email}}" @endif>
</div>
<div class="form-group">
    <label for="password" class=" form-control-label">Password</label>
    <input type="password" id="password" name="password" placeholder="Enter the (new) password" class="form-control">
</div>
<div class="form-group">
    <label for="role" class=" form-control-label">Role</label>
    <select id="role" name="role" class="form-control">
        <option value="2">Employee</option>
        <option value="3">Student</option>
    </select>
</div>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- MAIN CONTENT-->

    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            Overview Users
                            <a href="{{route('user.create')}}" class="btn btn-primary float-right">Add new user</a>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <td>Name</td>
                                    <td>Email</td>
                                    <td>Role</td>
                                    <td>Added on</td>
                                    <td>Rented artworks</td>
                                    <td>#</td>
                                    <td>#</td>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->role->name}}</td>
                                        <td>{{Carbon\Carbon::parse($user->created_at)->format('d-m-Y')}}</td>
                                        <td>{{$user->orders()->where('paid',true)->count()}}</td>
                                        <td><a href="{{route('user.edit',$user->id)}}">edit</a></td>
                                        <td>
                                            {{Form::open(['route'=>['user.destroy', $user], 'method'=>'delete'])}}
                                              <button class='btn btn-danger' type="submit" onclick="return confirm('are you sure?')">delete</button>
                                            {{Form::close()}}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection