routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {

Route::get('logout',function(){
    Session::flush();
    Auth::logout();
    return redirect(route('login'));
});

Route::get('/', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('art','ArtController');
Route::delete('art-photo-delete/{artPhoto}', 'ArtController@deletePhoto')->name('art.photo.delete');
Route::get('order', 'OrderController@index')->name('order.index');

Route::get('student/art', 'Student\ArtController@index')->name('student.art.index');
Route::get('student/art/{art}', 'Student\ArtController@show')->name('student.art.show');

Route::get('rent-art/{art}', 'Student\ArtController@rent')->name('student.art.rent');
Route::post('rent-art/{art}', 'Student\ArtController@confirm')->name('student.art.confirm');

Route::get('order-success/{order}', 'Student\OrderController@success')->name('order.success');
Route::get('student/order', 'Student\OrderController@index')->name('student.order.index');
Route::get('send-back/{order}', 'Student\OrderController@sendBack')->name('student.order.send.back');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('CoolAdmin-master/js/main.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('CoolAdmin-master/css/theme.css') }}" rel="stylesheet">
    <link href="{{ asset('CoolAdmin-master/css/font-face.css') }}" rel="stylesheet">

    <!-- Theme -->
    <link href="{{ asset('CoolAdmin-master/vendor/animsition/animsition.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css')  }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/wow/animate.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/css-hamburgers/hamburgers.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/slick/slick.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/select2/select2.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.css') }}" rel="stylesheet" media="all">

</head>
<body class="animsition">
<div class="page-wrapper">
    <!-- HEADER MOBILE-->
    <header class="header-mobile d-block d-lg-none">
        <div class="header-mobile__bar">
            <div class="container-fluid">
                <div class="header-mobile-inner">
                    <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>
        @include('layouts.mobile-sidebar')
    </header>
    <!-- END HEADER MOBILE-->

    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
        <div class="logo">
            <a href="{{route('home')}}">
                <img src="{{ asset('art-logo.jpg') }}" alt="Novi Kunstuitleen Logo" width="86px"/>
            </a>
        </div>
        <div class="menu-sidebar__content js-scrollbar1">
            @include('layouts.sidebar')
        </div>
    </aside>
    <!-- END MENU SIDEBAR-->

    <!-- PAGE CONTAINER-->
    <div class="page-container">
        <!-- HEADER DESKTOP-->
        @include('layouts.nav')
        <!-- HEADER DESKTOP-->
    <div class="main-content">
        <div class="container">
          <div class="row">
            <div class="col-12">
              @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
              <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
            </div>
            @endif


            @if ($message = Session::get('error'))
            <div class="alert alert-danger alert-block">
              <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
              </div>
            @endif


            @if ($message = Session::get('warning'))
            <div class="alert alert-warning alert-block">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <strong>{{ $message }}</strong>
            </div>
            @endif


            @if ($message = Session::get('info'))
            <div class="alert alert-info alert-block">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <strong>{{ $message }}</strong>
            </div>
            @endif


            @if ($errors->any())
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">×</button>
              Please check the form below for errors
            </div>
            @endif
            </div>
          </div>
        </div>
            @yield('content')
        </div>

        <!-- END PAGE CONTAINER-->
    </div>

</div>

<!-- Jquery JS-->
<script src="{{ asset('CoolAdmin-master/vendor/jquery-3.2.1.min.js') }}"></script>
<!-- Bootstrap JS-->
<script src="{{ asset('CoolAdmin-master/vendor/bootstrap-4.1/popper.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.js') }}"></script>
<!-- Vendor JS       -->
<script src="{{ asset('CoolAdmin-master/vendor/slick/slick.min.js') }}">
</script>
<script src="{{ asset('CoolAdmin-master/vendor/wow/wow.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/animsition/animsition.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js') }}">
</script>
<script src="{{ asset('CoolAdmin-master/vendor/counter-up/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/counter-up/jquery.counterup.min.js') }}">
</script>
<script src="{{ asset('CoolAdmin-master/vendor/circle-progress/circle-progress.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/chartjs/Chart.bundle.min.js') }}"></script>
<script src="{{ asset('CoolAdmin-master/vendor/select2/select2.min.js') }}">
</script>

<!-- Main JS-->
<script src="{{ asset('CoolAdmin-master/js/main.js') }}"></script>

@yield('javascript')

</body>
</html>

resources/views/layouts/mobile-sidebar.blade.php
@if(Auth::check())
    <nav class="navbar-mobile">
        <div class="container-fluid">
            <ul class="navbar-mobile__list list-unstyled">
              @if(Auth::user()->role->value === 'admin' || Auth::user()->role->value === 'employee')
              <li>
                  <a href="{{route('art.index')}}">
                      <i class="fas fa-table"></i>Artworks @if(Auth::user()->role->value === 'admin') (employee) @endif</a>
              </li>
              <li>
                  <a href="{{route('order.index')}}">
                      <i class="fas fa-table"></i>Orders</a>
              </li>
              @endif
              @if(Auth::user()->role->value === 'admin' || Auth::user()->role->value === 'student')
              <li>
                  <a href="{{route('student.art.index')}}">
                      <i class="fas fa-table"></i>Artworks @if(Auth::user()->role->value === 'admin') (student) @endif</a>
              </li>
              <li>
                  <a href="{{route('student.order.index')}}">
                      <i class="fas fa-table"></i>My Orders</a>
              </li>
              @endif
            </ul>
        </div>
    </nav>
@endif

resources/views/layouts/nav.blade.php
<header class="header-desktop">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="header-wrap">
                <div class="header-button account-button">
                    <div class="account-wrap">
                        <div class="account-item clearfix js-item-menu">
                            <div class="image">
                                {{--                                <img src="{{ asset('CoolAdmin-master/images/icon/avatar-02.jpg') }}images/icon/avatar-01.jpg" alt="John Doe" />--}}
                            </div>
                            <div class="content">
                                @if(Auth::check())
                                    <a class="js-acc-btn" href="#">{{Auth::user()->name}}</a>
                                @else
                                    <a href="{{route('login')}}">My Account</a>

                                @endif
                            </div>

                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    @if(Auth::check())
                                        <div class="content">
                                            <h5 class="name">
                                                <a href="#">{{Auth::user()->name}}</a>
                                            </h5>
                                            <span class="email">{{Auth::user()->email}}</span>
                                        </div>
                                    @endif
                                </div>
                                @if(Auth::check())

                                <div class="account-dropdown__body">
                                        <div class="account-dropdown__item">
                                            <a href="@if(Auth::user()->role === 'student'){{route('student.order.index')}}@else{{route('order.index')}}@endif">
                                                <i class="zmdi zmdi-money-box"></i>Orders</a>
                                        </div>
                                </div>
                                <div class="account-dropdown__footer">
                                    <a href="{{route('logout')}}">
                                        <i class="zmdi zmdi-power"></i>Logout</a>
                                </div>
                                @else
                                    <div class="account-dropdown__footer">
                                        <a href="{{route('login')}}">
                                            <i class="zmdi zmdi-power"></i>Inloggen</a>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/layouts/old_app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/sidebar.blade.php
@if(Auth::check())
    <nav class="navbar-sidebar">
        <ul class="list-unstyled navbar__list">
            @if(Auth::user()->role->value === 'admin' || Auth::user()->role->value === 'employee')
            <li>
                <a href="{{route('art.index')}}">
                    <i class="fas fa-table"></i>Artworks @if(Auth::user()->role->value === 'admin') (employee) @endif</a>
            </li>
            <li>
                <a href="{{route('order.index')}}">
                    <i class="fas fa-table"></i>Orders</a>
            </li>
            @endif
            @if(Auth::user()->role->value === 'admin' || Auth::user()->role->value === 'student')
            <li>
                <a href="{{route('student.art.index')}}">
                    <i class="fas fa-table"></i>Artworks @if(Auth::user()->role->value === 'admin') (student) @endif</a>
            </li>
            <li>
                <a href="{{route('student.order.index')}}">
                    <i class="fas fa-table"></i>My Orders</a>
            </li>
            @endif
            @if(Auth::user()->role->value === 'admin')
            <li>
                <a href="{{route('user.index')}}">
                    <i class="fas fa-table"></i>Users</a>
            </li>
            @endif
        </ul>
    </nav>
@endif